language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - rbx
  - ree
  - ruby-head
  - rbx-18mode
  - rbx-19mode
  - jruby
matrix:
  allow_failures:
    - rvm: rbx
    - rvm: rbx-18mode
    - rvm: rbx-19mode
branches:
  only:
    - master
env: JRUBY_OPTS='--1.9'
